import os
import time
import logging
from typing import List, Optional
from fastapi import FastAPI, HTTPException, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field
from dotenv import load_dotenv

# Load env variables (if any) prior to importing settings / services
load_dotenv()

try:
    from backend.services.gemini_service import GeminiService
except ModuleNotFoundError:
    from services.gemini_service import GeminiService

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    handlers=[logging.StreamHandler()]
)
logger = logging.getLogger("backend.main")

app = FastAPI(
    title="Gemini AI Chatbot Backend",
    description="Production-grade API backend for running Gemini Chatbot applications.",
    version="1.0.0"
)

# CORS configuration
# Allowing any origin for local dev, but allowing override via env variables
allowed_origins = os.getenv("ALLOWED_ORIGINS", "*").split(",")

app.add_middleware(
    CORSMiddleware,
    allow_origins=allowed_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize services
gemini_service = GeminiService()

# --- Request/Response Models ---
class MessageModel(BaseModel):
    role: str = Field(
        ..., 
        description="Role of the message author. Supported roles are 'user' and 'assistant'."
    )
    content: str = Field(
        ..., 
        description="Content of the message. Cannot be empty."
    )

    class Config:
        json_schema_extra = {
            "example": {
                "role": "user",
                "content": "What is the capital of France?"
            }
        }

class ChatRequest(BaseModel):
    messages: List[MessageModel] = Field(
        ..., 
        description="Chronological message list representing the conversation history."
    )
    system_instruction: Optional[str] = Field(
        default=None, 
        description="Instruction context to guide the model's behavior/personality."
    )

    class Config:
        json_schema_extra = {
            "example": {
                "messages": [
                    {"role": "user", "content": "Hello"},
                    {"role": "assistant", "content": "Hi! How can I help you today?"},
                    {"role": "user", "content": "Tell me a joke."}
                ],
                "system_instruction": "You are a helpful assistant who always speaks like a pirate."
            }
        }

class ChatResponse(BaseModel):
    response: str = Field(..., description="The response generated by the Gemini model.")
    status: str = Field("success", description="Response status message.")

class HealthResponse(BaseModel):
    status: str = Field(..., description="Current system status (healthy/degraded)")
    gemini_configured: bool = Field(..., description="Indicates if backend has GEMINI_API_KEY loaded")
    model_configured: str = Field(..., description="Name of the configured Gemini model")

# --- Custom Middleware ---
@app.middleware("http")
async def log_requests_middleware(request: Request, call_next):
    """
    Middleware that logs request details, status codes, and execution durations.
    """
    start_time = time.time()
    path = request.url.path
    method = request.method
    logger.info(f"Incoming request: {method} {path}")
    
    try:
        response = await call_next(request)
        duration = time.time() - start_time
        logger.info(f"Completed request: {method} {path} | Status: {response.status_code} | Duration: {duration:.4f}s")
        return response
    except Exception as e:
        duration = time.time() - start_time
        logger.error(f"Failed request: {method} {path} | Error: {str(e)} | Duration: {duration:.4f}s", exc_info=True)
        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            content={"detail": "An internal server error occurred processing your request."}
        )

# --- Routes ---
@app.get("/health", response_model=HealthResponse, status_code=status.HTTP_200_OK)
async def health_check():
    """
    Verifies that the backend server is running and check if the Gemini API key is configured.
    """
    has_key = gemini_service.api_key is not None and len(gemini_service.api_key) > 0
    return HealthResponse(
        status="healthy" if has_key else "degraded",
        gemini_configured=has_key,
        model_configured=gemini_service.model_name
    )

@app.post("/chat", response_model=ChatResponse, status_code=status.HTTP_200_OK)
async def chat(request: ChatRequest):
    """
    Receives chat history, formats it, prompts Gemini, and returns the response.
    """
    # 1. Validate empty inputs
    if not request.messages:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Message history cannot be empty."
        )
        
    last_message = request.messages[-1].content.strip()
    if not last_message:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="The latest user message content cannot be empty or whitespace."
        )

    # Convert request models to dictionary list for the service
    msg_list = [{"role": msg.role, "content": msg.content} for msg in request.messages]

    try:
        # 2. Invoke service
        bot_response = await gemini_service.generate_response(
            messages=msg_list,
            system_instruction=request.system_instruction
        )
        return ChatResponse(response=bot_response, status="success")
        
    except ValueError as val_err:
        # Raised for missing configuration/invalid API keys or invalid request parameters
        logger.warning(f"Validation error in /chat: {str(val_err)}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(val_err)
        )
    except Exception as e:
        logger.error(f"Internal API error in /chat: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=f"Error communicating with Gemini service: {str(e)}"
        )
